#!/bin/bash
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/pl
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep 
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin 
grep bin /etc/passwd | wc -l
grep b
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /e
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/pas
grep bin /etc/passwd | wc -l
grep bin /etc/
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
g
grep bin /etc/passwd | wc -l
grep
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin 
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /et
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
gre
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

gr
grep bin /etc/passwd | wc -l


grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/pas
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grl
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etcgrep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/pas=
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -lgrep bin /etc/passwd | wc
rep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
gre
grep bin /etc/passwd | wc -lgrep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -lgrep bin /etc/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /etc
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l/passwd | wc -l

grep bin /etc/passwd | wc -l
grep bin /
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l
grep bin /etc/passwd | wc -l



